### ISSUE TITLE
Not working on Pd-extended 0.43.4

### ISSUE THREAD

**Issue by sebpiq** [chr15m/SyncJams#12]
Hi Chris!

I tried to get SyncJams working on Pd-extended and no success. There is a bunch of error messages, "object not found" and "bad arguments". Also the README for Pd seems to be outdated. There is no "netro" object for example (which is what I'd need :) )

**Comment by chr15m** [comment]
Hi @sebpiq! Pd-extended has not been updated for a few years and uses an outdated version of Pd core and is missing a bunch of internal objects such as `oscparse` and old versions of `netsend` and `netreceive`.

You're right that pure-data/README is outdated, I'll make a new issue. The information in that README about netsync and netro is not relevant to this project. Those were old objects from a previous iteration of this software. All of that functionality has been folded into the `syncjams` abstraction.
